"""Remove constraints for studying

Revision ID: 04bb3625f8f4
Revises: 3a5e61953372
Create Date: 2024-02-01 22:10:57.062690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04bb3625f8f4'
down_revision = '3a5e61953372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews_flashcards', schema=None) as batch_op:
        batch_op.drop_constraint('user_id_flashcard_id_unique', type_='unique')

    with op.batch_alter_table('reviews_sets', schema=None) as batch_op:
        batch_op.drop_constraint('user_id_set_id_unique', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews_sets', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_id_set_id_unique', ['user_id', 'set_id'])

    with op.batch_alter_table('reviews_flashcards', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_id_flashcard_id_unique', ['user_id', 'flashcard_id'])

    # ### end Alembic commands ###
