"""Add photo and notes fields

Revision ID: 0eb316aeecec
Revises: 7b60605a8c63
Create Date: 2023-11-26 19:51:02.134553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb316aeecec'
down_revision = '7b60605a8c63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_photo', sa.String(), nullable=True))
        batch_op.alter_column('subscription_date',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('subscription_date',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
        batch_op.drop_column('user_photo')

    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
