"""change fields sizes of flashcards

Revision ID: 2afec0b23636
Revises: 865ca52bd32c
Create Date: 2023-12-28 23:43:09.911950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2afec0b23636'
down_revision = '865ca52bd32c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.alter_column('term',
               existing_type=sa.VARCHAR(length=16384),
               type_=sa.String(length=524288),
               existing_nullable=False)
        batch_op.alter_column('definition',
               existing_type=sa.VARCHAR(length=16384),
               type_=sa.String(length=524288),
               existing_nullable=False)
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(length=16384),
               type_=sa.String(length=524288),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.String(length=524288),
               type_=sa.VARCHAR(length=16384),
               existing_nullable=True)
        batch_op.alter_column('definition',
               existing_type=sa.String(length=524288),
               type_=sa.VARCHAR(length=16384),
               existing_nullable=False)
        batch_op.alter_column('term',
               existing_type=sa.String(length=524288),
               type_=sa.VARCHAR(length=16384),
               existing_nullable=False)

    # ### end Alembic commands ###
