"""add organization_id to folders

Revision ID: 3578d955cce0
Revises: 1adcdaaf35a3
Create Date: 2024-01-14 19:20:02.421492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3578d955cce0'
down_revision = '1adcdaaf35a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.String(length=26), nullable=True))
        batch_op.alter_column('category_id',
               existing_type=sa.VARCHAR(length=26),
               nullable=True)
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['organization_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('category_id',
               existing_type=sa.VARCHAR(length=26),
               nullable=False)
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###
