"""Add unique contraints to review sets, flashcards

Revision ID: 3a5e61953372
Revises: 83510975b388
Create Date: 2024-02-01 20:06:45.303141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a5e61953372'
down_revision = '83510975b388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews_flashcards', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_id_flashcard_id_unique', ['user_id', 'flashcard_id'])

    with op.batch_alter_table('reviews_sets', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_id_set_id_unique', ['user_id', 'set_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews_sets', schema=None) as batch_op:
        batch_op.drop_constraint('user_id_set_id_unique', type_='unique')

    with op.batch_alter_table('reviews_flashcards', schema=None) as batch_op:
        batch_op.drop_constraint('user_id_flashcard_id_unique', type_='unique')

    # ### end Alembic commands ###
