"""Add creation_time of flashcrads

Revision ID: 4d25b4cd0e77
Revises: ab209013a93a
Create Date: 2024-02-05 20:23:34.503780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d25b4cd0e77'
down_revision = 'ab209013a93a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flashcard_creation_time', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.drop_column('flashcard_creation_time')

    # ### end Alembic commands ###
