"""Add verified field to folders

Revision ID: 5052abf484ed
Revises: e0b6a5f20d0b
Create Date: 2024-02-10 23:18:26.213592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5052abf484ed'
down_revision = 'e0b6a5f20d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_column('verified')

    # ### end Alembic commands ###
