"""Add subcategories to folders and sets

Revision ID: 7606d591d790
Revises: 9a7a18381db5
Create Date: 2024-01-27 17:10:08.571174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7606d591d790'
down_revision = '9a7a18381db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory_id', sa.String(length=26), nullable=True))
        batch_op.create_foreign_key(None, 'subcategories', ['subcategory_id'], ['subcategory_id'])

    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('set_subcategory', sa.String(length=26), nullable=True))
        batch_op.create_foreign_key(None, 'subcategories', ['set_subcategory'], ['subcategory_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('set_subcategory')

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subcategory_id')

    # ### end Alembic commands ###
