"""Remove creation_dates columns as we have a timestamp in the ulid primary key

Revision ID: 7b60605a8c63
Revises: 93b202987d29
Create Date: 2023-11-10 20:08:34.360584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b60605a8c63'
down_revision = '93b202987d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('comment_creation_date')

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_column('folder_creation_date')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('organization_creation_date')

    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.drop_column('set_creation_date')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_creation_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_creation_date', sa.VARCHAR(length=40), autoincrement=False, nullable=False))

    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('set_creation_date', sa.VARCHAR(length=40), autoincrement=False, nullable=False))

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_creation_date', sa.VARCHAR(length=40), autoincrement=False, nullable=False))

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_creation_date', sa.VARCHAR(length=40), autoincrement=False, nullable=False))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_creation_date', sa.VARCHAR(length=40), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
