"""Add unique constraint between category_id and subcategory_id

Revision ID: 83510975b388
Revises: a034119ebfd4
Create Date: 2024-01-30 19:43:02.823123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83510975b388'
down_revision = 'a034119ebfd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_subcategories', schema=None) as batch_op:
        batch_op.create_unique_constraint('category_subcategory_unique', ['category_id', 'subcategory_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_subcategories', schema=None) as batch_op:
        batch_op.drop_constraint('category_subcategory_unique', type_='unique')

    # ### end Alembic commands ###
