"""Add organization_id to sets

Revision ID: 865ca52bd32c
Revises: d50c948b4b46
Create Date: 2023-12-27 01:38:59.316738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865ca52bd32c'
down_revision = 'd50c948b4b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.String(length=26), nullable=True))
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['organization_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###
