"""Order categories

Revision ID: ab209013a93a
Revises: b6ea4e39384b
Create Date: 2024-02-03 00:20:35.775041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab209013a93a'
down_revision = 'b6ea4e39384b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    with op.batch_alter_table('category_subcategories', schema=None) as batch_op:
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_subcategories', schema=None) as batch_op:
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
