"""Add order of subcategories

Revision ID: b6ea4e39384b
Revises: 04bb3625f8f4
Create Date: 2024-02-02 22:58:21.081436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ea4e39384b'
down_revision = '04bb3625f8f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_subcategories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_subcategories', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
