"""Remove unique contrain user_id set_name

Revision ID: b8429abfab5e
Revises: 0b2de57176bc
Create Date: 2023-12-23 16:20:54.762851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8429abfab5e'
down_revision = '0b2de57176bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.drop_constraint('sets_user_id_set_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.create_unique_constraint('sets_user_id_set_name_key', ['user_id', 'set_name'])

    # ### end Alembic commands ###
