"""Update reviews_flashcards table

Revision ID: bab471bd86b8
Revises: 2afec0b23636
Create Date: 2024-01-13 13:23:28.364140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab471bd86b8'
down_revision = '2afec0b23636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews_flashcards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviews_flashcards_id', sa.String(length=26), primary_key=True))
        batch_op.drop_constraint('reviews_flashcards_set_id_fkey', type_='foreignkey')
        batch_op.drop_column('liked_flashcard_id')
        batch_op.drop_column('set_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews_flashcards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('set_id', sa.VARCHAR(length=26), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('liked_flashcard_id', sa.VARCHAR(length=26), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('reviews_flashcards_set_id_fkey', 'sets', ['set_id'], ['set_id'])
        batch_op.drop_column('reviews_flashcards_id')

    # ### end Alembic commands ###
