"""Make term and definition not null

Revision ID: c9f2de05c161
Revises: b8429abfab5e
Create Date: 2023-12-24 19:00:25.495655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f2de05c161'
down_revision = 'b8429abfab5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.alter_column('term',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
        batch_op.alter_column('definition',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.alter_column('definition',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('term',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)

    # ### end Alembic commands ###
