"""Add verfied column to sets

Revision ID: e0b6a5f20d0b
Revises: 4d25b4cd0e77
Create Date: 2024-02-10 23:07:55.523548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b6a5f20d0b'
down_revision = '4d25b4cd0e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.drop_column('verified')

    # ### end Alembic commands ###
