services:
  py-api:
    build:
      context: ./zapomnigo-backend
      dockerfile: Dockerfile
    container_name: py-api
    env_file: ".env"
    ports:
      - "8000:8000"
    volumes:
      - ./zapomnigo-backend/data/certs:/app/data/certs
      - ./zapomnigo-backend/shared:/app/src/shared

    networks:
      - zapomnigo-network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    depends_on:
      - py-api
    networks:
      - zapomnigo-network
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1m

  celery-workers:
    build:
      context: ./zapomnigo-backend
      dockerfile: src/celery_task_queue/celery_workers/Dockerfile
    container_name: celery-workers
    env_file:
      - ".env"
    depends_on:
      - py-api
      - redis
    networks:
      - zapomnigo-network

  celery-beat:
    build:
      context: ./zapomnigo-backend
      dockerfile: src/celery_task_queue/celery_beat/Dockerfile
    container_name: celery-beat
    env_file:
      - ".env"
    depends_on:
      - py-api
      - redis
      - celery-workers
    networks:
      - zapomnigo-network

  react-app:
     build: ./zapomnigo-client
     container_name: react-app
     env_file:
       - ".env"
     ports:
       - "80:80"
       - "443:443"
     volumes:
       - ./zapomnigo-client/data/certs:/etc/nginx/certs
     networks:
       - zapomnigo-network

networks:
  zapomnigo-network:
    driver: bridge